name: Build and Release

on:
  push:
    branches:
      - main  # 适应你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: APT安装依赖
        run: |
          sudo apt update
          sudo apt install curl vim wget gnupg dpkg apt-transport-https lsb-release ca-certificates tar zstd -y

      - name: 安装GO环境
        run: |
          wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
          echo "export PATH=\$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          source $GITHUB_ENV
          go version

      - name: 部署Xcaddy
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update
          sudo apt install -y xcaddy

      - name: 编译
        run: |
          xcaddy build --with github.com/caddyserver/cache-handler --with github.com/ueffel/caddy-brotli --with github.com/caddyserver/transform-encoder --with github.com/RussellLuo/caddy-ext/ratelimit --with github.com/caddy-dns/cloudflare

      - name: Package and Upload
        run: |
          sudo tar -czvf caddy.tar.gz ./caddy # 将可执行文件打包为 tar.gz
      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: caddy
          path: ./caddy.tar.gz
      - name: 发布到 Releases
        uses: ncipollo/release-action@v1
        with:
          name: "你的发布名称"
          artifacts: "caddy.zip" # 输入你的 artifact 文件名，多个文件用逗号分隔
          bodyFile: "body.md" # 用于描述此次发布的 markdown 文件
          token: ${{ secrets.REPO_TOKEN }} # GitHub 自动生成的 token  
          tag: ${{ github.ref }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./caddy.tar.gz" # 这里写你要上传的构件路径
          token: ${{ secrets.REPO_TOKEN }} # 这里使用了GitHub Actions的内置secrets
          draft: false # 这表示创建的是一个正式版的Release，而不是草稿
          prerelease: false # 这表示创建的是一个正式版的Release，而不是预发布版
          replaceArtifacts: true # 这表示如果同名的构件已经存在，就替换它           
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#       env:
#          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
#        with:
#          tag_name: v1.0.0  # 创建发布的标签名称
 #         release_name: Release v1.0.0  # 发布的名称
#          body: |
 #           Release v1.0.0
  #        draft: false
  #        prerelease: false
#
  #    - name: Upload Release Asset
 #       id: upload_release_asset
 #       uses: actions/upload-release-asset@v1
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
 #       with:
 #         upload_url: ${{ steps.create_release.outputs.upload_url }}
 #         asset_path: ./caddy.tar.gz
   #       asset_name: ${{ steps.create_release.outputs.filename }}
 #         asset_content_type: application/gzip