name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'TEST-VERSION'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GO_VERSION: 1.25
        #CADDY_VERSION: v2.10.0
        CADDY_VERSION: master
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
          
    steps:
      - name: 导入仓库内容
        uses: actions/checkout@v3

      - name: 加载版本号
        run: echo "VERSION=$(cat TEST-VERSION)" >> $GITHUB_ENV  

      - name: APT安装依赖
        run: |
          sudo apt update
          sudo apt install curl vim wget gnupg dpkg apt-transport-https lsb-release ca-certificates tar zstd -y

      - name: 部署Go环境
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 部署Xcaddy
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update
          sudo apt install -y xcaddy
          
      - name: 打包编译-EXTRA
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          xcaddy build ${{ env.CADDY_VERSION }} \
            --with github.com/caddyserver/cache-handler \
            --with github.com/WJQSERVER/souin-storages/simplefs/caddy \
            --with github.com/ueffel/caddy-brotli \
            --with github.com/caddyserver/transform-encoder \
            --with github.com/WJQSERVER/caddy-ext/ratelimit \
            --with github.com/caddy-dns/cloudflare@master \
            --with github.com/WJQSERVER/caddy-ja4h \
            --with github.com/mholt/caddy-webdav
          tar -czvf caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz caddy
          tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.zst caddy
  
      - name: 打包编译-PURE
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          xcaddy build ${{ env.CADDY_VERSION }}
          tar -czvf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.gz caddy
          tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.zst caddy  
        
      - name: 上传至Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.VERSION }}
          artifacts: ./caddy*.tar.gz, ./caddy*.tar.zst
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
          allowUpdates: true
        env:
          export PATH: $PATH:/usr/local/go/bin

  package:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: 加载版本号
      run: echo "VERSION=$(cat TEST-VERSION)" >> $GITHUB_ENV  

    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install curl wget tar unzip zstd -y

    - name: 打包 EXTRA
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        sudo wget -O caddyd-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz https://github.com/WJQSERVER/caddy/releases/download/${{ env.VERSION }}/caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        sudo tar -xzvf caddyd-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        sudo mkdir -p caddy_web
        sudo mv caddy caddy_web/
        sudo cp -r pages caddy_web/
        sudo cp LICENSE_caddy caddy_web/
        sudo tar -czf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pages.tar.gz -C caddy_web .
        sudo tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pages.tar.zst -C caddy_web .

    - name: 打包 Pure
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        sudo wget -O caddyd-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.gz https://github.com/WJQSERVER/caddy/releases/download/${{ env.VERSION }}/caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.gz
        sudo tar -xzvf caddyd-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.gz
        sudo mkdir -p caddy_web
        sudo mv caddy caddy_web/
        sudo cp -r pages caddy_web/
        sudo cp LICENSE_caddy caddy_web/
        sudo tar -czf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pages-pure.tar.gz -C caddy_web .
        sudo tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pages-pure.tar.zst -C caddy_web .

    - name: 上传Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.VERSION }}
        artifacts: ./caddy*pages.tar.gz, ./caddy*pages.tar.zst, ./caddy*pages-l4.tar.gz, ./caddy*pages-l4.tar.zst, ./caddy*pages-pure.tar.gz, ./caddy*pages-pure.tar.zst
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.VERSION }}
        allowUpdates: true
      env:
        export PATH: $PATH:/usr/local/go/bin