name: Build and Release

on:
  push:
    branches:
      - main  # 适应你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: APT安装依赖
        run: |
          sudo apt update
          sudo apt install curl vim wget gnupg dpkg apt-transport-https lsb-release ca-certificates tar zstd -y

      - name: 安装GO环境
        run: |
          wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
          echo "export PATH=\$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          source $GITHUB_ENV
          go version

      - name: 部署Xcaddy
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update
          sudo apt install -y xcaddy

      - name: 编译
        run: |
          xcaddy build --with github.com/caddyserver/cache-handler --with github.com/ueffel/caddy-brotli --with github.com/caddyserver/transform-encoder --with github.com/RussellLuo/caddy-ext/ratelimit --with github.com/caddy-dns/cloudflare

      - name: Package and Upload
        run: |
          sudo tar -czvf caddy.tar.gz ./caddy # 将可执行文件打包为 tar.gz
      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: caddy
          path: ./caddy.tar.gz


      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: 1.1.5
          artifacts: ./caddy.tar.gz
          body: caddy
          token: ${{ secrets.REPO_TOKEN }}
          tag: 1.1.5
        env:
          export PATH: $PATH:/usr/local/go/bin

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: caddy.tar.gz
          asset_name: caddy.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

    