name: 打包
on: 
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install curl wget tar unzip zstd -y
    - name: 拉取文件
      run: |
        sudo wget -O caddyd.tar.gz https://github.com/WJQSERVER/caddy/releases/download/2.8.4/caddy.tar.gz
        sudo tar -xzvf caddyd.tar.gz
        sudo mkdir -p caddy_web
        sudo mv caddy caddy_web/

    - name: Package /pages directory
      run: | 
        sudo cp -r pages caddy_web/
        sudo tar -czf caddy_web.tar.gz -C caddy_web .
        sudo tar -I zstd -cf caddy_web.tar.zst -C caddy_web .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-files
        path: |
          caddy_web.tar.gz
          caddy_web.tar.zst
