name: 打包
on: 
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: 安装依赖
      run: |
        apt update
        apt install curl wget tar unzip zstd -y
    - name: 拉取文件
      run: |
        curl -s -L https://github.com/WJQSERVER/caddy/releases/download/2.8.4/caddy.tar.gz -o caddyd.tar.gz
        tar -xzf caddyd.tar
        mkdir -p caddy
        mv caddy caddy/

    - name: Package /pages directory
      run: | 
        cp -r pages caddy/
        tar -czf caddy_web.tar.gz -C caddy .
        tar -I zstd -cf caddy_web.tar.zst -C caddy .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-files
        path: |
          caddy_web.tar.gz
          caddy_web.tar.zst
